import { ContextEntry } from "./types";

export function generatePrompt(entries: ContextEntry[], featureId: string): string {
    if (entries.length === 0) return `No context found for feature: ${featureId}.`;

    const latest = entries[entries.length - 1];
    const timeAgo = getTimeAgo(latest.timestamp);

    let prompt = `## ContextKeeper: Active Feature Context\n\n`;
    prompt += `**Feature:** ${featureId}\n`;
    prompt += `**Last session:** ${timeAgo}\n`;
    prompt += `**Last Author:** ${latest.author}\n\n`;

    prompt += `### Current Goals & Intent\n${latest.task}\n\n`;

    if (latest.approaches.length > 0) {
        prompt += `### What's Been Tried (Approaches)\n`;
        latest.approaches.forEach((a) => (prompt += `- ${a}\n`));
        prompt += `\n`;
    }

    // Aggregate decisions across the feature history (deduplicated)
    const allDecisions = Array.from(new Set(entries.flatMap(e => e.decisions)));
    if (allDecisions.length > 0) {
        prompt += `### Architectural & Core Decisions\n`;
        allDecisions.forEach((d) => (prompt += `- ${d}\n`));
        prompt += `\n`;
    }

    prompt += `### Current State (Where we left off)\n${latest.currentState}\n\n`;

    if (latest.nextSteps.length > 0) {
        prompt += `### Next Steps\n`;
        latest.nextSteps.forEach((s, i) => (prompt += `${i + 1}. ${s}\n`));
        prompt += `\n`;
    }

    if (latest.blockers && latest.blockers.length > 0) {
        prompt += `### Blockers / Open Questions\n`;
        latest.blockers.forEach((b) => (prompt += `- ⚠️ ${b}\n`));
        prompt += `\n`;
    }

    if (latest.filesChanged.length > 0) {
        prompt += `### Files Changed Recently\n`;
        latest.filesChanged.forEach((f) => (prompt += `- ${f}\n`));
        prompt += `\n`;
    }

    if (latest.recentCommits.length > 0) {
        prompt += `### Recent Commits\n`;
        latest.recentCommits.forEach((c) => (prompt += `- ${c}\n`));
        prompt += `\n`;
    }

    // Add history summary if multiple sessions
    if (entries.length > 1) {
        prompt += `### Timeline (${entries.length} sessions)\n`;
        entries
            .slice(-5)
            .reverse()
            .forEach((e) => {
                prompt += `- [${new Date(e.timestamp).toLocaleString()}] ${e.author}: ${e.task}\n`;
            });
        prompt += `\n`;
    }

    prompt += `---\n*Generated by ContextKeeper*`;

    return prompt;
}

function getTimeAgo(timestamp: string): string {
    const diff = Date.now() - new Date(timestamp).getTime();
    const minutes = Math.floor(diff / 60000);
    if (minutes < 60) return `${minutes} minutes ago`;
    const hours = Math.floor(minutes / 60);
    if (hours < 24) return `${hours} hours ago`;
    const days = Math.floor(hours / 24);
    return `${days} days ago`;
}
